version: '1.0'

services:
  mission-id:
    build: ./
    container_name: 'mission-id'
    networks:
      - mission-gateway_mission
      - mission-db_postgres
    environment:
      POSTGRES_HOST: postgres-project
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: mission-project
      POSTGRES_SCHEMA: public
      POSTGRES_PASSWORD: private_password
      POSTGRES_USERNAME: postgres
      APPLICATION_PORT: 80
networks:
  mission-gateway_mission:
    external: true
  mission-db_postgres:
    external: true